"""add index book copy status

Revision ID: 01c69a7e61c4
Revises: 802288265990
Create Date: 2026-08-29 21:31:09.393014

"""
from alembic import op
import sqlalchemy as sa


revision = '01c69a7e61c4'
down_revision = '802288265990'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BookCopies', schema=None) as batch_op:
        batch_op.create_index('ix_book_copies_book_id_status', ['book_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BookCopies', schema=None) as batch_op:
        batch_op.drop_index('ix_book_copies_book_id_status')

    # ### end Alembic commands ###
