"""Change BorrowDetails PK

Revision ID: 0c19773151e6
Revises: 7f6c6703a4c4
Create Date: 2026-08-30 02:17:02.454464

"""
from alembic import op
import sqlalchemy as sa


revision = '0c19773151e6'
down_revision = '7f6c6703a4c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
