"""add anhBia to Book

Revision ID: 23c6d305d146
Revises: 0017
Create Date: 2026-08-27 09:02:28.336742

"""
from alembic import op
import sqlalchemy as sa


revision = '23c6d305d146'
down_revision = '0017'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anhBia', sa.Unicode(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.drop_column('anhBia')

    # ### end Alembic commands ###
