"""increase_anhbia_length

Revision ID: 534849c03802
Revises: 23c6d305d146
Create Date: 2026-08-27 21:21:13.853843

"""
from alembic import op
import sqlalchemy as sa


revision = '534849c03802'
down_revision = '23c6d305d146'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.alter_column('anhBia',
               existing_type=sa.NVARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=2048),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.alter_column('anhBia',
               existing_type=sa.Unicode(length=2048),
               type_=sa.NVARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    # ### end Alembic commands ###
