"""Increase copy_id length

Revision ID: 7f6c6703a4c4
Revises: 01c69a7e61c4
Create Date: 2026-08-30 01:59:27.668493

"""
from alembic import op
import sqlalchemy as sa


revision = '7f6c6703a4c4'
down_revision = '01c69a7e61c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BookCopies', schema=None) as batch_op:
        batch_op.alter_column('copy_id',
               existing_type=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=50),
               existing_nullable=False)

    with op.batch_alter_table('BorrowDetails', schema=None) as batch_op:
        batch_op.alter_column('copy_id',
               existing_type=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=50),
               existing_nullable=True)

    with op.batch_alter_table('DatTruoc', schema=None) as batch_op:
        batch_op.alter_column('copy_id',
               existing_type=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DatTruoc', schema=None) as batch_op:
        batch_op.alter_column('copy_id',
               existing_type=sa.Unicode(length=50),
               type_=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    with op.batch_alter_table('BorrowDetails', schema=None) as batch_op:
        batch_op.alter_column('copy_id',
               existing_type=sa.Unicode(length=50),
               type_=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    with op.batch_alter_table('BookCopies', schema=None) as batch_op:
        batch_op.alter_column('copy_id',
               existing_type=sa.Unicode(length=50),
               type_=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
