"""add_book_copies

Revision ID: 802288265990
Revises: d85ac5075d18
Create Date: 2026-08-29 21:08:57.604731

"""
from alembic import op
import sqlalchemy as sa


revision = '802288265990'
down_revision = 'd85ac5075d18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BookCopies',
    sa.Column('copy_id', sa.Unicode(length=20), nullable=False),
    sa.Column('book_id', sa.Unicode(length=20), nullable=False),
    sa.Column('status', sa.Unicode(length=50), nullable=False),
    sa.CheckConstraint("status IN ('Có sẵn', 'Đang mượn', 'Đang giữ chỗ', 'Hỏng', 'Mất')", name='ck_book_copies_status'),
    sa.ForeignKeyConstraint(['book_id'], ['Books.ma'], ),
    sa.PrimaryKeyConstraint('copy_id')
    )
    with op.batch_alter_table('BookCopies', schema=None) as batch_op:
        batch_op.create_index('ix_book_copies_book_id', ['book_id'], unique=False)

    with op.batch_alter_table('BorrowDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('copy_id', sa.Unicode(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'BookCopies', ['copy_id'], ['copy_id'])

    with op.batch_alter_table('DatTruoc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('copy_id', sa.Unicode(length=20), nullable=True))
        batch_op.add_column(sa.Column('han_nhan', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'BookCopies', ['copy_id'], ['copy_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DatTruoc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('han_nhan')
        batch_op.drop_column('copy_id')

    with op.batch_alter_table('BorrowDetails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('copy_id')

    with op.batch_alter_table('BookCopies', schema=None) as batch_op:
        batch_op.drop_index('ix_book_copies_book_id')

    op.drop_table('BookCopies')
    # ### end Alembic commands ###
