"""make_anhbia_required

Revision ID: d85ac5075d18
Revises: 534849c03802
Create Date: 2026-08-27 21:32:03.227195

"""
from alembic import op
import sqlalchemy as sa


revision = 'd85ac5075d18'
down_revision = '534849c03802'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.alter_column('anhBia',
               existing_type=sa.NVARCHAR(length=2048, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.alter_column('anhBia',
               existing_type=sa.NVARCHAR(length=2048, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)

    # ### end Alembic commands ###
